name: Scanner
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - run-scanner

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ISV_SETUP_BEST_PRACTICES }}
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "21"
      - name: Restore node cache
        id: cache-npm
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.npm
            ~/.sf
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Run SF Scanner
        run: sf scanner run -- -- -- --target force-app --json -s 4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
